#!/usr/bin/env node
// Generates every Axis logo asset from the single drawn master,
// assets/axis-mask.svg. Edit the geometry there and the colours below, then
// run `pnpm run assets`. Nothing here is hand-maintained.

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

// --- colour options -------------------------------------------------------

const colors = {
    // The wave is a left-to-right gradient across the 32-unit mark.
    waveFrom: '#22D3EE',
    waveTo: '#A78BFA',
    // The crossing bar, muted so the wave reads first. One value per surface.
    barOnDark: '#94A3B8',
    barOnLight: '#475569',
    // The tile's rounded backdrop, and the banner wordmark.
    tileBackground: '#0B1220',
    tileRadius: 7,
    wordmark: '#22D3EE',
    // The mono variant inherits the host's text colour; the bar is dimmed.
    monoBarOpacity: 0.55,
};

// --- the master -----------------------------------------------------------

const mask = readFileSync(join(root, 'assets/axis-mask.svg'), 'utf8');

const pathData = id => {
    const match = mask.match(new RegExp(`id="${id}"[^>]*\\sd="([^"]+)"`));
    if (!match) throw new Error(`assets/axis-mask.svg has no path with id="${id}"`);
    return match[1];
};

const bar = [pathData('bar-1'), pathData('bar-2')];
const wave = pathData('wave');

const indent = (lines, by) => lines.map(line => ' '.repeat(by) + line).join('\n');

/** The mark's three blobs: the bar in `barFill`, then the wave in `waveFill`. */
const blobs = (barFill, waveFill, pad = 2, barAttrs = '') =>
    indent(
        [
            `<g fill="${barFill}"${barAttrs}>`,
            ...bar.map(d => `  <path d="${d}"/>`),
            `</g>`,
            `<path d="${wave}" fill="${waveFill}"/>`,
        ],
        pad,
    );

/** The gradient the wave is painted with, as a <defs> block. */
const gradient = (id, pad = 2) =>
    indent(
        [
            `<defs>`,
            `  <linearGradient id="${id}" x1="1.00" y1="0" x2="31.00" y2="0" gradientUnits="userSpaceOnUse">`,
            `    <stop offset="0" stop-color="${colors.waveFrom}"/>`,
            `    <stop offset="1" stop-color="${colors.waveTo}"/>`,
            `  </linearGradient>`,
            `</defs>`,
        ],
        pad,
    );

const generated =
    'Generated by scripts/generate-assets.mjs from assets/axis-mask.svg — do not edit.';

/** A plain 32x32 icon: gradient wave over a solid bar. */
const icon = ({
    gradientId,
    barFill,
    viewBox = '0 0 32 32',
    note,
}) => `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${viewBox}">
  <title>Axis</title>
  <!-- ${generated}
       ${note} -->
${gradient(gradientId)}
${blobs(barFill, `url(#${gradientId})`)}
</svg>
`;

// --- the assets -----------------------------------------------------------

const assets = {
    // Root brand assets.
    'assets/axis-mark.svg': icon({
        gradientId: 'axisMarkWave',
        barFill: colors.barOnDark,
        note: 'The mark on its own, for anywhere a bare logo is wanted.',
    }),

    'assets/axis-mono.svg': `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">
  <title>Axis</title>
  <!-- ${generated}
       Single-colour: inherits the host's text colour via currentColor. -->
${blobs('currentColor', 'currentColor', 2, ` opacity="${colors.monoBarOpacity}"`)}
</svg>
`,

    'assets/axis-tile.svg': `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">
  <title>Axis</title>
  <!-- ${generated}
       The mark on its own rounded backdrop, for app-icon style slots. -->
${gradient('axisTileWave')}
  <rect width="32" height="32" rx="${colors.tileRadius}" fill="${colors.tileBackground}"/>
${blobs(colors.barOnLight, 'url(#axisTileWave)')}
</svg>
`,

    // The wordmark: "a" and "is" with the mark standing in for the "x",
    // scaled from the 32-unit geometry onto the x-height band.
    'assets/axis-banner.svg': `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 103 56" width="205" height="112" role="img" aria-label="axis">
  <title>axis</title>
  <!-- ${generated} -->
${gradient('axisBannerWave')}
  <g font-family="Inter, 'SF Pro Display', -apple-system, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif" font-size="30" font-weight="400" letter-spacing="-0.5" fill="${colors.wordmark}">
    <text x="32" y="39.5" text-anchor="end">a</text>
    <text x="64.64" y="39.5">is</text>
  </g>
  <g transform="translate(33.05 16.04) scale(0.9546)">
${blobs(colors.barOnDark, 'url(#axisBannerWave)', 4)}
  </g>
</svg>
`,

    // Extension icons. Copied into packages/extension rather than referenced
    // because vsce packs only that folder — a path out of it would not ship.
    'packages/extension/icons/axis-dark.svg': icon({
        gradientId: 'axisFileDark',
        barFill: colors.barOnDark,
        note: 'Recoloured for a dark file tree.',
    }),

    'packages/extension/icons/axis-light.svg': icon({
        gradientId: 'axisFileLight',
        barFill: colors.barOnLight,
        note: 'Recoloured for a light file tree.',
    }),

    // The toolbar variants inset the mark by 2 units a side via the viewBox,
    // so it clears the 16px button edge the way a codicon does.
    'packages/extension/icons/axis-action-dark.svg': icon({
        gradientId: 'axisActionDark',
        barFill: colors.barOnDark,
        viewBox: '-2 -2 36 36',
        note: 'Recoloured for a dark toolbar and inset by 2 units a side.',
    }),

    'packages/extension/icons/axis-action-light.svg': icon({
        gradientId: 'axisActionLight',
        barFill: colors.barOnLight,
        viewBox: '-2 -2 36 36',
        note: 'Recoloured for a light toolbar and inset by 2 units a side.',
    }),
};

for (const [path, svg] of Object.entries(assets)) {
    writeFileSync(join(root, path), svg);
    console.log(`wrote ${path}`);
}
